/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 * openapi-contract-sha256: b9f3c36db07b06197373473b4fbc3c76bf59b740d2cd79bde1ece3a60a15c9a2
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user profile summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/v1/check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        idempotencyKey?: string;
                        interaction?: components["schemas"]["ActivityInteractionProgress"];
                        /** @enum {string} */
                        theme?: "office" | "restroom" | "daydream";
                    };
                };
            };
            responses: {
                /** @description Started check-in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CheckInSession"];
                            error: null;
                        };
                    };
                };
                /** @description Active check-in already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/check-ins/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        interaction?: components["schemas"]["ActivityInteractionProgress"];
                    };
                };
            };
            responses: {
                /** @description Finished check-in with rewards */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CheckInFinishResult"];
                            error: null;
                        };
                    };
                };
                /** @description Check-in not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/check-ins/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active check-in or null */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CheckInSession"] | null;
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leaderboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    window: "daily" | "weekly" | "monthly" | "all_time";
                    limit?: number;
                    scope?: "global" | "friends" | "squad" | "company";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Leaderboard page and current user rank context */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["LeaderboardResponse"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/social/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Friend code, relationships, and group memberships */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["SocialSummary"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/social/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        friendCode: string;
                    };
                };
            };
            responses: {
                /** @description Updated social summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["SocialSummary"];
                            error: null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/social/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        recipientUserId: string;
                        /** @enum {string} */
                        reactionType: "tissue" | "like";
                    };
                };
            };
            responses: {
                /** @description Reaction result and aggregate counts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["SocialReactionResult"];
                            error: null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/progression/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Authenticated user progression summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ProgressionSummary"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/progression/{period}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path: {
                    period: "daily" | "weekly";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Goal period reward claim result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ProgressionClaimResult"];
                            error: null;
                        };
                    };
                };
                /** @description Goal period is incomplete */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/beans/collection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User bean collection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["BeanCollection"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/beans/draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        idempotencyKey?: string;
                    };
                };
            };
            responses: {
                /** @description Bean draw result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["BeanDrawResult"];
                            error: null;
                        };
                    };
                };
                /** @description No draw chance available */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/beans/fragments/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fragment exchange result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                fragments: number;
                                drawChances: number;
                            };
                            error: null;
                        };
                    };
                };
                /** @description Insufficient fragments */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/beans/showcase/{position}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    position: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        beanId: string;
                    };
                };
            };
            responses: {
                /** @description Showcase updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bean is not owned */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Achievement list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AchievementList"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cosmetics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Owned cosmetics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CosmeticInventory"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cosmetics/{id}/equip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Equipped cosmetic */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CosmeticEquipResult"];
                            error: null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        category?: "rest" | "game" | "office_theater" | "physical" | "imagination";
                    };
                };
            };
            responses: {
                /** @description Assigned random activity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ActivityAssignment"];
                            error: null;
                        };
                    };
                };
                /** @description No eligible activity available */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    category?: "rest" | "game" | "office_theater" | "physical" | "imagination";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Activity catalog with current eligibility */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ActivityCatalog"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recent activity completion history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ActivityHistory"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/{assignmentId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assignmentId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        idempotencyKey?: string;
                    };
                };
            };
            responses: {
                /** @description Activity completion result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ActivityCompleteResult"];
                            error: null;
                        };
                    };
                };
                /** @description Activity assignment not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Activity expired or interaction incomplete */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/{assignmentId}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assignmentId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason?: components["schemas"]["ActivitySkipReason"];
                    };
                };
            };
            responses: {
                /** @description Skipped activity assignment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ActivityAssignment"];
                            error: null;
                        };
                    };
                };
                /** @description Activity assignment not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string;
            message: string;
            requestId?: string;
            traceId?: string;
        };
        Health: {
            ok: boolean;
            service: string;
            requestId: string;
            traceId: string;
        };
        UserSummary: {
            id: string;
            displayName: string;
            equippedBadge?: string | null;
            equippedTitle?: string | null;
            stats: {
                totalSessions: number;
                currentStreakDays: number;
                drawChances: number;
                drawProgress: number;
            };
        };
        CheckInSession: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "active" | "completed" | "cancelled" | "invalidated";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string | null;
            durationSeconds: number | null;
            eligibleDurationSeconds: number | null;
            rewarded: boolean;
        };
        CheckInFinishResult: {
            session: components["schemas"]["CheckInSession"];
            reward: {
                score: number;
                drawProgress: number;
                drawChancesGranted?: number;
                rewarded: boolean;
                achievementsUnlocked?: components["schemas"]["AchievementUnlock"][];
            };
        };
        RewardSummary: {
            score: number;
            drawProgressGranted: number;
            drawProgress: number;
            drawChancesGranted: number;
            achievementsUnlocked: string[];
        };
        LeaderboardItem: {
            rank: number;
            userId: string | null;
            displayName: string;
            equippedBadge?: string | null;
            equippedTitle?: string | null;
            score: number;
            reactions: {
                tissue: number;
                like: number;
            };
        };
        LeaderboardResponse: {
            /** @enum {string} */
            window: "daily" | "weekly" | "monthly" | "all_time";
            /** Format: date-time */
            windowStart: string;
            /** @enum {string} */
            scope: "global" | "friends" | "squad" | "company";
            suppressed: boolean;
            suppressionReason: string | null;
            items: components["schemas"]["LeaderboardItem"][];
            currentUser: components["schemas"]["LeaderboardItem"] | null;
        };
        SocialSummary: {
            friendCode: string;
            friends: {
                userId: string;
                displayName: string;
            }[];
            squad: {
                id?: string;
                name?: string;
                inviteCode?: string;
                memberCount?: number;
            } | null;
            company: {
                id?: string;
                name?: string;
                inviteCode?: string;
                anonymousAlias?: string;
                memberCount?: number;
            } | null;
            reactions: {
                dailyLimit: number;
                sentToday: number;
                remainingToday: number;
                resetTimezone: string;
            };
        };
        SocialReactionResult: {
            created: boolean;
            /** @enum {string} */
            reactionType: "tissue" | "like";
            counts: {
                tissue: number;
                like: number;
            };
            remainingToday: number;
            resultTitle: string;
            resultCopy: string;
        };
        ProgressionGoal: {
            /** @enum {string} */
            code: "check_in" | "activity" | "bean_draw" | "rest_minutes" | "active_days";
            title: string;
            description: string;
            current: number;
            target: number;
            /** @enum {string} */
            unit: "times" | "minutes" | "days";
            completed: boolean;
        };
        ProgressionGoalPeriod: {
            /** @enum {string} */
            period: "daily" | "weekly";
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
            completed: number;
            total: number;
            allCompleted: boolean;
            rewardClaimed: boolean;
            /** Format: date-time */
            claimedAt: string | null;
            reward: {
                score: number;
                drawProgress: number;
            };
            goals: components["schemas"]["ProgressionGoal"][];
        };
        ProgressionClaimResult: {
            /** @enum {string} */
            period: "daily" | "weekly";
            awarded: boolean;
            /** Format: date-time */
            claimedAt: string;
            reward: {
                score: number;
                drawProgress: number;
                drawChancesGranted: number;
            };
            progression: {
                level: number;
                experience: number;
                currentLevelExperience: number;
                nextLevelExperience: number;
                progressPercent: number;
                previousLevel: number;
                currentLevel: number;
                leveledUp: boolean;
            };
        };
        ProgressionSummary: {
            level: number;
            experience: number;
            currentLevelExperience: number;
            nextLevelExperience: number;
            progressPercent: number;
            currentStreakDays: number;
            longestStreakDays: number;
            lifetime: {
                totalSessions: number;
                eligibleRestMinutes: number;
                completedActivities: number;
                collectedBeanTypes: number;
                unlockedAchievements: number;
            };
            dailyGoals: components["schemas"]["ProgressionGoalPeriod"];
            weeklyGoals: components["schemas"]["ProgressionGoalPeriod"];
            nextActions: components["schemas"]["ProgressionNextAction"][];
        };
        ProgressionNextAction: {
            /** @enum {string} */
            code: "start_check_in" | "complete_activity" | "draw_bean" | "claim_daily_reward" | "claim_weekly_reward";
            title: string;
            description: string;
            actionLabel: string;
            /** @enum {string} */
            targetSection: "home" | "activities" | "beans" | "rankings" | "profile";
            priority: number;
            rewardPreview: {
                score: number;
                drawProgress: number;
                drawChances: number;
            } | null;
        };
        Bean: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** @enum {string} */
            rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
            /** @enum {string} */
            theme: "office" | "restroom" | "daydream";
            description: string;
            quantity: number;
            owned: boolean;
        };
        BeanCollection: {
            drawChances: number;
            drawProgress: number;
            fragments: number;
            fragmentExchangeCost: number;
            pityCount: number;
            pityThreshold: number;
            summary: {
                collected: number;
                total: number;
                percent: number;
                nextAction: string;
            };
            nextTarget: {
                /** Format: uuid */
                id: string;
                code: string;
                name: string;
                /** @enum {string} */
                rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
                /** @enum {string} */
                theme: "office" | "restroom" | "daydream";
                hint: string;
            } | null;
            beans: components["schemas"]["Bean"][];
            themes: {
                /** @enum {string} */
                theme: "office" | "restroom" | "daydream";
                collected: number;
                total: number;
            }[];
            combinations: {
                code: string;
                name: string;
                owned: number;
                required: number;
                completed: boolean;
            }[];
            showcase: {
                position: number;
                bean: components["schemas"]["Bean"];
            }[];
        };
        BeanDrawResult: {
            bean: components["schemas"]["Bean"];
            duplicate: boolean;
            fragmentsGranted: number;
            pityTriggered: boolean;
            pityCount: number;
            remainingDrawChances: number;
            resultTitle: string;
            resultCopy: string;
            nextHint: string;
            achievementsUnlocked?: components["schemas"]["AchievementUnlock"][];
        };
        AchievementUnlock: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** Format: date-time */
            unlockedAt: string;
            rewards: {
                score: number;
                drawProgress: number;
                drawChances: number;
                cosmetic: string | null;
            };
        };
        Achievement: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description: string;
            /** @enum {string} */
            ruleType: "first_checkin" | "streak" | "total_duration" | "activity_count" | "collection_count" | "weekly_top_rank";
            rewardConfig: {
                [key: string]: unknown;
            };
            progress: {
                current: number;
                target: number;
                /** @enum {string} */
                unit: "count" | "days" | "minutes" | "rank";
                percent: number;
                completed: boolean;
            };
            /** @enum {string} */
            category: "new_user" | "check_in" | "activity" | "bean_draw" | "leaderboard" | "social";
            /** @enum {string} */
            rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
            unlockSummary: string;
            recommendationWeight: number;
            todayFriendly: boolean;
            actionHint: {
                /** @enum {string} */
                section: "home" | "activities" | "beans" | "leaderboards" | "profile";
                label: string;
            };
            /** Format: date-time */
            unlockedAt: string | null;
            /** Format: date-time */
            rewardClaimedAt: string | null;
        };
        AchievementRecommendations: {
            nearest: components["schemas"]["AchievementRecommendation"][];
            today: components["schemas"]["AchievementRecommendation"][];
            long_term: components["schemas"]["AchievementRecommendation"][];
        };
        AchievementRecommendation: components["schemas"]["Achievement"] & {
            /** @enum {string} */
            recommendationGroup: "nearest" | "today" | "long_term";
            recommendationReason: string;
            remainingEffortLabel: string;
            /** @enum {string} */
            targetSection: "home" | "activities" | "beans" | "leaderboards" | "profile";
        };
        AchievementList: {
            achievements: components["schemas"]["Achievement"][];
            recommendations: components["schemas"]["AchievementRecommendations"];
        };
        Cosmetic: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description: string;
            /** @enum {string} */
            cosmeticType: "badge" | "title";
            /** @enum {string} */
            rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
            unlockSummary: string;
        };
        OwnedCosmetic: components["schemas"]["Cosmetic"] & {
            owned: boolean;
            /** Format: date-time */
            unlockedAt: string | null;
            equipped: boolean;
        };
        CosmeticInventory: {
            equippedBadge: components["schemas"]["Cosmetic"] | null;
            equippedTitle: components["schemas"]["Cosmetic"] | null;
            cosmetics: components["schemas"]["OwnedCosmetic"][];
        };
        CosmeticEquipResult: {
            cosmetic: components["schemas"]["Cosmetic"];
        };
        ActivityInteractionStep: {
            id: string;
            /** @enum {string} */
            type: "ack" | "timer" | "choice" | "mini_game";
            title: string;
            description: string;
            required: boolean;
            durationSeconds?: number;
            options?: {
                id: string;
                label: string;
                resultText: string;
            }[];
            correctOptionId?: string;
            gameCode?: string;
            requiredResult?: string;
        };
        ActivityInteraction: {
            /** @enum {string} */
            mode: "guided";
            estimatedSeconds: number;
            /** @enum {string} */
            proofPolicy: "none" | "optional_photo" | "optional_location" | "external_game";
            flavorLabel: string;
            steps: components["schemas"]["ActivityInteractionStep"][];
            completionFeedback: string[];
            resultSummary: {
                title: string;
                copy: string;
            };
        };
        ActivityInteractionSummary: {
            stepCount: number;
            estimatedSeconds: number;
            hasTimer: boolean;
            hasChoice: boolean;
            hasMiniGame: boolean;
            /** @enum {string} */
            proofPolicy: "none" | "optional_photo" | "optional_location" | "external_game";
            flavorLabel: string;
        };
        ActivityInteractionProgress: {
            completedStepIds?: string[];
            timerSeconds?: {
                [key: string]: number;
            };
            choiceAnswers?: {
                [key: string]: string;
            };
            miniGameResults?: {
                [key: string]: {
                    passed?: boolean;
                    score?: number;
                };
            };
        };
        /** @enum {string} */
        ActivitySkipReason: "too_much_work" | "not_interested" | "not_convenient" | "want_weirder" | "other";
        ActivityPresentation: {
            badge: string;
            /** @enum {string} */
            tone: "absurd" | "calm" | "game" | "physical" | "daydream";
            accentColor: string;
            headline: string;
            scene: string;
            prompt: string;
            statLabel: string;
            statValue: string;
        };
        ActivityAssignment: {
            /** Format: uuid */
            assignmentId: string;
            code: string;
            title: string;
            description: string;
            /** @enum {string} */
            category: "rest" | "game" | "office_theater" | "physical" | "imagination";
            /** @enum {string} */
            difficulty: "easy" | "normal" | "hard";
            /** @enum {string} */
            status: "active" | "completed" | "skipped" | "expired";
            rewardPreview: {
                score: number;
                drawProgress: number;
            };
            presentation: components["schemas"]["ActivityPresentation"];
            interaction: components["schemas"]["ActivityInteraction"];
            interactionSummary: components["schemas"]["ActivityInteractionSummary"];
            /** Format: date-time */
            assignedAt: string;
            /** Format: date-time */
            completedAt: string | null;
            /** Format: date-time */
            expiresAt: string | null;
            rewarded: boolean;
            /** @enum {string} */
            recommendationReason?: "PREFERRED_CATEGORY" | "TRY_SOMETHING_NEW" | "MATCHES_HISTORY" | "AVAILABLE_NOW" | "ACTIVE_ASSIGNMENT";
            recommendationExplanation?: string;
        };
        ActivityCatalogItem: {
            /** Format: uuid */
            templateId: string;
            code: string;
            title: string;
            description: string;
            /** @enum {string} */
            category: "rest" | "game" | "office_theater" | "physical" | "imagination";
            /** @enum {string} */
            difficulty: "easy" | "normal" | "hard";
            rewardPreview: {
                score: number;
                drawProgress: number;
            };
            presentation: components["schemas"]["ActivityPresentation"];
            interactionSummary: components["schemas"]["ActivityInteractionSummary"];
            eligible: boolean;
            cooldownRemainingSeconds: number;
            completedCount: number;
            /** Format: date-time */
            lastCompletedAt: string | null;
            /** Format: date-time */
            checkedAt: string;
        };
        ActivityCatalog: {
            /** @enum {string|null} */
            selectedCategory: "rest" | "game" | "office_theater" | "physical" | "imagination" | null;
            categories: ("rest" | "game" | "office_theater" | "physical" | "imagination")[];
            items: components["schemas"]["ActivityCatalogItem"][];
        };
        ActivityHistory: {
            items: components["schemas"]["ActivityAssignment"][];
        };
        ActivityCompleteResult: {
            assignment: components["schemas"]["ActivityAssignment"];
            feedback: string;
            resultTitle: string;
            resultCopy: string;
            reward: {
                score: number;
                drawProgress: number;
                drawChancesGranted: number;
                rewarded: boolean;
                reason: string | null;
                achievementsUnlocked: components["schemas"]["AchievementUnlock"][];
            };
        };
    };
    responses: never;
    parameters: {
        RequestId: string;
        TraceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
