/**
 * This file was auto-generated by openapi-typescript.
 * openapi-contract-sha256: 678045f7126fbc8caa2ad9ddefe03e5d729971bae3aae16f9b939770f2af9b74
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user profile summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/v1/check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        idempotencyKey?: string;
                    };
                };
            };
            responses: {
                /** @description Started check-in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CheckInSession"];
                            error: null;
                        };
                    };
                };
                /** @description Active check-in already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/check-ins/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        idempotencyKey?: string;
                    };
                };
            };
            responses: {
                /** @description Finished check-in with rewards */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CheckInFinishResult"];
                            error: null;
                        };
                    };
                };
                /** @description Check-in not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/check-ins/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active check-in or null */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CheckInSession"] | null;
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leaderboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    window: "daily" | "weekly" | "monthly" | "all_time";
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Leaderboard page and current user rank context */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["LeaderboardResponse"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/beans/collection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User bean collection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["BeanCollection"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/beans/draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                    "X-Trace-Id"?: components["parameters"]["TraceId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        idempotencyKey?: string;
                    };
                };
            };
            responses: {
                /** @description Bean draw result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["BeanDrawResult"];
                            error: null;
                        };
                    };
                };
                /** @description No draw chance available */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Achievement list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AchievementList"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cosmetics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Owned cosmetics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CosmeticInventory"];
                            error: null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cosmetics/{id}/equip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Equipped cosmetic */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CosmeticEquipResult"];
                            error: null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Assigned random activity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ActivityAssignment"];
                            error: null;
                        };
                    };
                };
                /** @description No eligible activity available */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/{assignmentId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assignmentId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        idempotencyKey?: string;
                    };
                };
            };
            responses: {
                /** @description Activity completion result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ActivityCompleteResult"];
                            error: null;
                        };
                    };
                };
                /** @description Activity assignment not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Activity expired */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string;
            message: string;
            requestId?: string;
            traceId?: string;
        };
        Health: {
            ok: boolean;
            service: string;
            requestId: string;
            traceId: string;
        };
        UserSummary: {
            id: string;
            displayName: string;
            equippedBadge?: string | null;
            equippedTitle?: string | null;
            stats: {
                totalSessions: number;
                currentStreakDays: number;
                drawChances: number;
                drawProgress: number;
            };
        };
        CheckInSession: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "active" | "completed" | "cancelled" | "invalidated";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string | null;
            durationSeconds: number | null;
            eligibleDurationSeconds: number | null;
            rewarded: boolean;
        };
        CheckInFinishResult: {
            session: components["schemas"]["CheckInSession"];
            reward: {
                score: number;
                drawProgress: number;
                drawChancesGranted?: number;
                rewarded: boolean;
                achievementsUnlocked?: components["schemas"]["AchievementUnlock"][];
            };
        };
        RewardSummary: {
            score: number;
            drawProgressGranted: number;
            drawProgress: number;
            drawChancesGranted: number;
            achievementsUnlocked: string[];
        };
        LeaderboardItem: {
            rank: number;
            userId: string;
            displayName: string;
            equippedBadge?: string | null;
            equippedTitle?: string | null;
            score: number;
        };
        LeaderboardResponse: {
            /** @enum {string} */
            window: "daily" | "weekly" | "monthly" | "all_time";
            /** Format: date-time */
            windowStart: string;
            items: components["schemas"]["LeaderboardItem"][];
            currentUser: components["schemas"]["LeaderboardItem"] | null;
        };
        Bean: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** @enum {string} */
            rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
            description: string;
            quantity: number;
            owned: boolean;
        };
        BeanCollection: {
            drawChances: number;
            drawProgress: number;
            beans: components["schemas"]["Bean"][];
        };
        BeanDrawResult: {
            bean: components["schemas"]["Bean"];
            duplicate: boolean;
            remainingDrawChances: number;
            achievementsUnlocked?: components["schemas"]["AchievementUnlock"][];
        };
        AchievementUnlock: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** Format: date-time */
            unlockedAt: string;
            rewards: {
                score: number;
                drawProgress: number;
                drawChances: number;
                cosmetic: string | null;
            };
        };
        Achievement: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description: string;
            /** @enum {string} */
            ruleType: "first_checkin" | "streak" | "total_duration" | "activity_count" | "collection_count" | "weekly_top_rank";
            rewardConfig: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            unlockedAt: string | null;
            /** Format: date-time */
            rewardClaimedAt: string | null;
        };
        AchievementList: {
            achievements: components["schemas"]["Achievement"][];
        };
        Cosmetic: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description: string;
            /** @enum {string} */
            cosmeticType: "badge" | "title";
            /** @enum {string} */
            rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
        };
        OwnedCosmetic: components["schemas"]["Cosmetic"] & {
            /** Format: date-time */
            unlockedAt: string;
            equipped: boolean;
        };
        CosmeticInventory: {
            equippedBadge: components["schemas"]["Cosmetic"] | null;
            equippedTitle: components["schemas"]["Cosmetic"] | null;
            cosmetics: components["schemas"]["OwnedCosmetic"][];
        };
        CosmeticEquipResult: {
            cosmetic: components["schemas"]["Cosmetic"];
        };
        ActivityAssignment: {
            /** Format: uuid */
            assignmentId: string;
            title: string;
            description: string;
            /** @enum {string} */
            difficulty: "easy" | "normal" | "hard";
            /** @enum {string} */
            status: "active" | "completed" | "skipped" | "expired";
            rewardPreview: {
                score: number;
                drawProgress: number;
            };
            /** Format: date-time */
            assignedAt: string;
            /** Format: date-time */
            completedAt: string | null;
            /** Format: date-time */
            expiresAt: string | null;
            rewarded: boolean;
        };
        ActivityCompleteResult: {
            assignment: components["schemas"]["ActivityAssignment"];
            reward: {
                score: number;
                drawProgress: number;
                drawChancesGranted: number;
                rewarded: boolean;
                reason: string | null;
                achievementsUnlocked: components["schemas"]["AchievementUnlock"][];
            };
        };
    };
    responses: never;
    parameters: {
        RequestId: string;
        TraceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
